name: Daily-Builder

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:

  Daily-Builder:
    name: Check
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.20
      uses: actions/setup-go@v1
      with:
        go-version: 1.20
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: Test
      run: make daily_test
    - name: Build
      run: make build